language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - easy_install distribute
    - python -m pip install -r requirements.txt
    # - python -m pip install -r requirements-test.txt
script:
    - python manage.py test